maintainer        'Matthew Todd'
maintainer_email  'matthew.todd@gmail.com'
license           'Apache 2.0'
description       'Installs and configures postfix for client or outbound relayhost, or to do SASL auth'
version           '0.1'
